apiVersion: v1
kind: ServiceAccount
metadata:
  name: tuck-injector
  namespace: tuck-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tuck-injector
rules:
  # Read pods to validate injection requests.
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tuck-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tuck-injector
subjects:
  - kind: ServiceAccount
    name: tuck-injector
    namespace: tuck-system
