version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (*net/http.Response).Body.Close
        - (*database/sql.DB).Close
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
        - fmt.Sscanf
    staticcheck:
      checks:
        - "all"
        - "-SA1019"
        - "-QF1003"
        - "-SA9003"
        - "-S1039"
        - "-S1005"
        - "-ST1000"
        - "-ST1003"
