apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tuck.fullname" . }}-server
  namespace: {{ include "tuck.namespace" . }}
  labels:
    {{- include "tuck.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
