{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tuck.fullname" . }}-server
  namespace: {{ include "tuck.namespace" . }}
  labels:
    {{- include "tuck.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "tuck.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
  ports:
    - name: api
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
      protocol: TCP
    {{- if .Values.server.cluster.enabled }}
    - name: raft
      port: 8201
      targetPort: 8201
      protocol: TCP
    {{- end }}
{{- end }}
